### ISSUE TITLE
Fails to run with websocket error

### ISSUE THREAD

**Issue by p-b-west** [minimal-xyz/minimal-shadow-cljs-browser#1]
Here's the error message:

```
VM219:164 WebSocket connection to 'ws://localhost:49601/worker/ws/app/9e42c276-ded5-40c5-a845-8471f7251553/e0e7e644-3401-4562-b483-5495f5a8cdaa/browser' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

Then the console says:

```
DEVTOOLS: disconnected!
```

Running a repl in a new terminal with

```bash
$ yarn shadow-cljs cljs-repl app
```

and attempting to execute any clojure code fails with

```
There is no connected JS runtime.
```

**Comment by tiye** [comment]
So the problem is your WebSocket connection is not established. Can you add logs from shadow-cljs which many show more details about what is happening.

Besides, shadow-cljs has updates in the past months, you can also try deleting `target/shadow-cljs/` folder and upgrade shadow-cljs to try again.

**Comment by tiye** [comment]
Just updated a bit in https://github.com/minimal-xyz/minimal-shadow-cljs-browser/commit/b5f33e62d0062eae2cf49504e771f2e688dbe14c .

Run `yarn` and you should get updates...

**Comment by p-b-west** [comment]
Where are the logs? Or do you mean system.log?

**Comment by p-b-west** [comment]
It's working now. Thanks. There was probably user error in there.

**Comment by tiye** [comment]
Logs that shadow-cljs printed after `yarn watch`... At least it contains some informations about how is it running.
