### ISSUE TITLE
delete yarn.lock

### ISSUE THREAD

**Issue by thheller** [minimal-xyz/minimal-shadow-cljs-browser#2]
This pins the shadow-cljs version to whatever was current when you installed it. Meaning that you'd need to update this template for every new version. Should rather just delete the lock file and let yarn/npm install the latest version.

**Comment by tiye** [comment]
Agreed for a demo project.

**Comment by tiye** [comment]
Ignored `yarn.lock` in https://github.com/minimal-xyz/minimal-shadow-cljs-browser/commit/8c024d6fac80d14c6bd20e252783c5381d84acb2 .
